const roundMoney = (value) => Math.round((value + Number.EPSILON) * 100) / 100;
const normalized = (value) => String(value ?? '').trim().toLowerCase();

function zonedClock(at, timeZone = 'Asia/Makassar') {
  const parts = new Intl.DateTimeFormat('en-US', { timeZone, weekday:'short', hour:'2-digit', minute:'2-digit', hourCycle:'h23' }).formatToParts(at);
  const values = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return { day:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(values.weekday), time:`${values.hour}:${values.minute}` };
}
function isActive(promo, at) {
  const time=at.getTime(); if(promo.status!=='PUBLISHED'||time<new Date(promo.startsAt).getTime()||time>new Date(promo.endsAt).getTime())return false;
  const schedule=promo.condition?.schedule;if(!schedule)return true;const clock=zonedClock(at,schedule.timeZone);
  if(Array.isArray(schedule.daysOfWeek)&&schedule.daysOfWeek.length&&!schedule.daysOfWeek.map(Number).includes(clock.day))return false;
  if(schedule.timeStart&&schedule.timeEnd){if(schedule.timeStart<=schedule.timeEnd&&(clock.time<schedule.timeStart||clock.time>schedule.timeEnd))return false;if(schedule.timeStart>schedule.timeEnd&&clock.time<schedule.timeStart&&clock.time>schedule.timeEnd)return false;}else{if(schedule.timeStart&&clock.time<schedule.timeStart)return false;if(schedule.timeEnd&&clock.time>schedule.timeEnd)return false;}return true;
}
function selectPriceRule(product,customerGroupId,baseQty){const eligible=product.priceRules.filter((rule)=>baseQty>=rule.minBaseQty&&(rule.customerGroupId===null||rule.customerGroupId===customerGroupId));if(!eligible.length)throw new Error(`Harga tidak ditemukan untuk ${product.name}`);return eligible.sort((a,b)=>{const specificity=Number(Boolean(b.customerGroupId))-Number(Boolean(a.customerGroupId));return b.minBaseQty-a.minBaseQty||specificity;})[0];}
function matchesTarget(line,condition={}){const productIds=condition.productIds??[],categories=condition.categories??(condition.category?[condition.category]:[]),brands=condition.brands??[];if(productIds.length&&!productIds.includes(line.productId))return false;if(categories.length&&!categories.some((value)=>normalized(value)===normalized(line.category)))return false;if(brands.length&&!brands.some((value)=>normalized(value)===normalized(line.brand)))return false;return true;}
function eligibleForPromo(line,promo,customerGroupId,subtotal){const condition=promo.condition??{};if(Array.isArray(condition.customerGroupIds)&&condition.customerGroupIds.length&&!condition.customerGroupIds.includes(customerGroupId))return false;if(Number(condition.minBasketSubtotal??0)>subtotal)return false;if(line.baseQty<Number(condition.minBaseQty??0))return false;return matchesTarget(line,condition);}
function snapshot(promo,discount,reason){return{id:promo.id,code:promo.code,version:promo.version,discount:roundMoney(discount),reason};}
function applyDiscount(line,promo,amount,reason){if(!(amount>0)||line._locked)return 0;if(line.promotions.length&&!promo.stackable)return 0;const applied=roundMoney(Math.min(amount,line.gross-line.discount));if(!(applied>0))return 0;line.discount=roundMoney(line.discount+applied);line.promotions.push(snapshot(promo,applied,reason));if(!promo.stackable)line._locked=true;return applied;}
function distribute(lines,promo,amount,reason){const eligible=lines.filter((line)=>!line._locked&&(!line.promotions.length||promo.stackable)&&line.gross>line.discount),available=eligible.reduce((sum,line)=>sum+line.gross-line.discount,0);if(!(available>0)||!(amount>0))return;let remaining=roundMoney(Math.min(amount,available));eligible.forEach((line,index)=>{const share=index===eligible.length-1?remaining:roundMoney(Math.min(remaining,amount*((line.gross-line.discount)/available)));remaining=roundMoney(remaining-applyDiscount(line,promo,share,reason));});}
function itemPromo(promo,lines,group,subtotal){const reward=promo.reward??{};for(const line of lines.filter((item)=>eligibleForPromo(item,promo,group,subtotal))){let discount=0,reason='';if(reward.type==='PERCENT_ITEM'){discount=Math.min(line.gross*(Number(reward.value)/100),Number(reward.maxDiscount??Number.MAX_SAFE_INTEGER));reason=`${reward.value}% untuk minimal ${promo.condition?.minBaseQty??0} satuan dasar`;}else if(reward.type==='FIXED_ITEM'){discount=Number(reward.value)*line.baseQty;reason=`Potongan ${reward.value} per satuan dasar`;}else if(reward.type==='SPECIAL_PRICE'){discount=line.gross-Number(reward.value)*line.baseQty;reason=`Harga khusus ${reward.value} per satuan dasar`;}applyDiscount(line,promo,discount,reason);}}
function orderPromo(promo,lines,group,subtotal){const eligible=lines.filter((line)=>eligibleForPromo(line,promo,group,subtotal)),base=eligible.reduce((sum,line)=>sum+line.gross-line.discount,0),discount=Math.min(base*(Number(promo.reward?.value)/100),Number(promo.reward?.maxDiscount??Number.MAX_SAFE_INTEGER));distribute(eligible,promo,discount,`${promo.reward?.value}% dari belanja yang memenuhi syarat`);}
function fixedOrderPromo(promo,lines,group,subtotal){const condition=promo.condition??{};if(Array.isArray(condition.customerGroupIds)&&condition.customerGroupIds.length&&!condition.customerGroupIds.includes(group))return;const eligible=lines.filter((line)=>matchesTarget(line,condition));if(!eligible.length)return;const qty=eligible.reduce((sum,line)=>sum+line.baseQty,0),minQty=Number(condition.minBaseQty??0),minBasket=Number(condition.minBasketSubtotal??0);if(qty<minQty||subtotal<minBasket)return;const reward=promo.reward??{};let count=1;if(reward.repeatMode==='MULTIPLE'){const limits=[];if(minQty>0)limits.push(Math.floor(qty/minQty));if(minBasket>0)limits.push(Math.floor(subtotal/minBasket));count=limits.length?Math.min(...limits):1;const cap=Number(reward.repeatCap??0);if(cap>0)count=Math.min(count,cap);}if(!(count>0))return;distribute(eligible,promo,Number(reward.value??0)*count,`Potongan tetap ${reward.value} (${reward.repeatMode==='MULTIPLE'?`${count} kelipatan`:'berlaku sekali'})`);}
function buyGetPromo(promo,lines,group,subtotal){const buyLines=lines.filter((line)=>eligibleForPromo(line,promo,group,subtotal)),reward=promo.reward??{},buyQty=Number(reward.buyQty??promo.condition?.minBaseQty??1),freeQty=Number(reward.freeQty??1),rewardIds=reward.productIds??[],rewardLines=rewardIds.length?lines.filter((line)=>rewardIds.includes(line.productId)):buyLines,same=!rewardIds.length||rewardLines.every((line)=>buyLines.some((buy)=>buy.productId===line.productId)),purchased=buyLines.reduce((sum,line)=>sum+line.baseQty,0);let remaining=(same?Math.floor(purchased/(buyQty+freeQty)):Math.floor(purchased/buyQty))*freeQty;for(const line of[...rewardLines].sort((a,b)=>a.baseUnitPrice-b.baseUnitPrice||a.productName.localeCompare(b.productName))){if(remaining<=0)break;const qty=Math.min(remaining,line.baseQty);if(applyDiscount(line,promo,qty*line.baseUnitPrice,`Beli ${buyQty} gratis ${freeQty}`)>0)remaining-=qty;}}
function bundlePromo(promo,lines){const bundle=promo.condition?.bundle??[];if(!bundle.length)return;const members=bundle.map((item)=>({...item,line:lines.find((line)=>line.productId===item.productId)}));if(members.some((item)=>!item.line||item.line._locked||(!promo.stackable&&item.line.promotions.length)))return;const count=Math.min(...members.map((item)=>Math.floor(item.line.baseQty/Number(item.qty))));if(!(count>0))return;const regular=members.reduce((sum,item)=>sum+item.line.baseUnitPrice*Number(item.qty),0)*count;distribute(members.map((item)=>item.line),promo,regular-Number(promo.reward?.value)*count,`Paket ${count} × ${promo.reward?.value}`);}
export function quoteBasket({lines,customerGroupId='retail',products,promotions,at=new Date()}){const quotedLines=lines.map((line)=>{const product=products.find((item)=>item.id===line.productId);if(!product)throw new Error(`Produk ${line.productId} tidak ditemukan`);const unit=product.units.find((item)=>item.id===line.unitId);if(!unit)throw new Error(`Satuan ${line.unitId} tidak ditemukan`);const baseQty=line.qty*unit.factor;if(!Number.isFinite(baseQty)||baseQty<=0)throw new Error('Jumlah harus lebih dari nol');const priceRule=selectPriceRule(product,customerGroupId,baseQty),gross=roundMoney(priceRule.unitPriceBase*baseQty);return{...line,productName:product.name,category:product.category,brand:product.brand,unitName:unit.name,baseQty,baseUnitPrice:Number(priceRule.unitPriceBase),priceRuleId:priceRule.id,gross,discount:0,promotions:[],_locked:false};}),subtotal=roundMoney(quotedLines.reduce((sum,line)=>sum+line.gross,0)),active=promotions.filter((promo)=>isActive(promo,at)).sort((a,b)=>b.priority-a.priority||String(a.code).localeCompare(String(b.code)));for(const promo of active){const type=promo.reward?.type??'PERCENT_ITEM';if(['PERCENT_ITEM','FIXED_ITEM','SPECIAL_PRICE'].includes(type))itemPromo(promo,quotedLines,customerGroupId,subtotal);if(type==='PERCENT_ORDER')orderPromo(promo,quotedLines,customerGroupId,subtotal);if(type==='FIXED_ORDER')fixedOrderPromo(promo,quotedLines,customerGroupId,subtotal);if(type==='BUY_X_GET_Y')buyGetPromo(promo,quotedLines,customerGroupId,subtotal);if(type==='BUNDLE_FIXED')bundlePromo(promo,quotedLines);}for(const line of quotedLines){line.total=roundMoney(line.gross-line.discount);delete line._locked;}const discountTotal=roundMoney(quotedLines.reduce((sum,line)=>sum+line.discount,0));return{lines:quotedLines,subtotal,discountTotal,grandTotal:roundMoney(subtotal-discountTotal),promotionEngineVersion:'2.1.0'};}
