export const PERMISSIONS = Object.freeze({
  POS_SELL: 'pos.sell',
  VIEW_COST: 'purchasing.view_cost',
  RECEIVE_PURCHASE: 'purchasing.receive',
  MANAGE_INVENTORY: 'inventory.manage',
  PROCESS_RETURN: 'sales.return',
  MANAGE_PRODUCTS: 'catalog.manage',
  MANAGE_PROMOTIONS: 'promotion.manage',
  VIEW_REPORTS: 'report.view',
  VIEW_AUDIT: 'audit.view',
  MANAGE_USERS: 'identity.manage',
  WORKFORCE_SELF: 'workforce.self',
  MANAGE_WORKFORCE: 'workforce.manage',
  MANAGE_APPROVALS: 'approval.manage',
  OWNER_FINANCE: 'finance.owner'
});

export const ROLE_PERMISSIONS = Object.freeze({
  OWNER: Object.values(PERMISSIONS),
  CASHIER: [PERMISSIONS.POS_SELL, PERMISSIONS.WORKFORCE_SELF],
  PURCHASING: [PERMISSIONS.VIEW_COST, PERMISSIONS.RECEIVE_PURCHASE, PERMISSIONS.WORKFORCE_SELF],
  WAREHOUSE: [PERMISSIONS.MANAGE_INVENTORY, PERMISSIONS.WORKFORCE_SELF],
  ADMIN: [PERMISSIONS.POS_SELL, PERMISSIONS.VIEW_COST, PERMISSIONS.RECEIVE_PURCHASE, PERMISSIONS.PROCESS_RETURN, PERMISSIONS.MANAGE_INVENTORY, PERMISSIONS.MANAGE_PRODUCTS, PERMISSIONS.MANAGE_PROMOTIONS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.VIEW_AUDIT, PERMISSIONS.WORKFORCE_SELF, PERMISSIONS.MANAGE_WORKFORCE, PERMISSIONS.MANAGE_APPROVALS]
});

export function permissionsFor(role) {
  return [...(ROLE_PERMISSIONS[role] ?? [])];
}

export function can(session, permission) {
  return Boolean(session?.permissions?.includes(permission));
}
